// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEufmjTiTobbbQ78S2WFzOIC46DwtAg_g',
    appId: '1:544834564896:web:bf3013cd08c0b7d8991d45',
    messagingSenderId: '544834564896',
    projectId: 'supply-wala-eb27f',
    authDomain: 'supply-wala-eb27f.firebaseapp.com',
    storageBucket: 'supply-wala-eb27f.firebasestorage.app',
    measurementId: 'G-HHP5ZM3DVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATxvFDxdd1yAQ6F5ee1nq18zpctC17grA',
    appId: '1:544834564896:android:935a35d381b7cf3b991d45',
    messagingSenderId: '544834564896',
    projectId: 'supply-wala-eb27f',
    storageBucket: 'supply-wala-eb27f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEufmjTiTobbbQ78S2WFzOIC46DwtAg_g',
    appId: '1:544834564896:web:e576b55c3d338857991d45',
    messagingSenderId: '544834564896',
    projectId: 'supply-wala-eb27f',
    authDomain: 'supply-wala-eb27f.firebaseapp.com',
    storageBucket: 'supply-wala-eb27f.firebasestorage.app',
    measurementId: 'G-WD5ST0KGXR',
  );
}
